---
## Change the name of the resource
## Default: use the chart name
# nameOverride:

pod:
  image: fabiolb/fabio
  tag: 1.5.10-go1.11.1
  hostNetwork: false
  hostPID: false
  securityContext:
    ## Whether the container should be run in "privileged" mode (essentially, root on the host)
    ## Ref: http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_securitycontext
    ## Default: false
    privileged:


properties: |-
  property.1=value-1
  property.2=value-2


service:
  name: fabio
  type: ClusterIP
  externalPort: 80
  internalPort: 9999
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"

## How many versions of the deployment to run on kubernetes
deployment:
  replicas: 1

resources:
  requests:
    cpu: "200m"
    memory: "128Mi"
  limits:
    cpu: "400m"
    memory: "512Mi"

probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
