---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}
data:
  fabio.properties: |-
{{ tpl .Values.properties . | indent 4 }}
